# Generated by Django 2.2.3 on 2019-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_view', '0002_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.CharField(max_length=255)),
                ('isi', models.TextField()),
            ],
        ),
    ]
