# Generated by Django 2.2.3 on 2019-07-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata_view', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
